// <auto-generated />
namespace zasz.me.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SoAnswers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SoAnswers));
        
        string IMigrationMetadata.Id
        {
            get { return "201209231312503_SoAnswers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
